# Generated by Django 6.0.2 on 2026-06-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_subtitle',
            field=models.CharField(default="VII–XI asrlardagi turkiy yozma merosning elektron to'plami", max_length=500),
        ),
    ]
