# Generated by Django 6.0.6 on 2026-06-11 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korpus', '0002_alter_sitesettings_site_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Muallif email'),
        ),
        migrations.AddField(
            model_name='monument',
            name='author_institution',
            field=models.CharField(blank=True, max_length=300, verbose_name='Muallif tashkiloti'),
        ),
        migrations.AddField(
            model_name='monument',
            name='author_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Muallif ismi'),
        ),
        migrations.AddField(
            model_name='monument',
            name='is_user_submission',
            field=models.BooleanField(default=False, verbose_name='Foydalanuvchi yuborgan'),
        ),
        migrations.CreateModel(
            name='MonumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('year', models.IntegerField(verbose_name='Yil (taxminiy)')),
                ('location', models.CharField(max_length=255, verbose_name='Joy')),
                ('script', models.CharField(choices=[('koktürk', "Ko'ktürk"), ('sogd', "So'g'd"), ("uyg'ur", "Uyg'ur"), ('arab', 'Arab'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Yozuv turi')),
                ('category', models.CharField(choices=[('bitiglar', 'Bitik toshlar'), ('qollanmalar', "Qo'llanmalar"), ('diniy', 'Diniy matnlar'), ('adabiy', 'Adabiy asarlar'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Kategoriya')),
                ('language', models.CharField(default="Ko'hna turkiy", max_length=100, verbose_name='Til')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.URLField(blank=True, verbose_name='Rasm URL (ixtiyoriy)')),
                ('transliteration', models.TextField(blank=True, verbose_name='Transliteratsiya (ixtiyoriy)')),
                ('translation', models.TextField(blank=True, verbose_name='Tarjima (ixtiyoriy)')),
                ('source_info', models.TextField(blank=True, verbose_name='Manba / adabiyot')),
                ('author_name', models.CharField(max_length=200, verbose_name='Ismingiz')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('author_institution', models.CharField(blank=True, max_length=300, verbose_name='Tashkilot / universitet')),
                ('author_bio', models.TextField(blank=True, verbose_name="O'zingiz haqingizda")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('reviewer_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt")),
                ('monument', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='korpus.monument', verbose_name='Yaratilgan yodgorlik')),
            ],
            options={
                'verbose_name': 'Taklif etilgan yodgorlik',
                'verbose_name_plural': 'Taklif etilgan yodgorliklar',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
