# "Ko'p uchraydigan so'zlar" rubrikasi uchun — korpusdagi qadimgi turkiy
# so'zlarning zamonaviy turkcha (Türkiye türkçesi) muqobili/izohi.
# Manba: standart turkologiya (Tekin, Clauson, Erdal) — Orxun-Yenisey bitiktoshlari,
# Irq Bitig, Xuastuanift va Oltin Yorug' matnlaridagi so'zlar.
# 27 ta so'z qo'shimcha ravishda bitig.kz ("Türik Bitig" — Qozog'iston Til qo'mitasi
# bazasi, Wayback Machine arxivi orqali, sayt joriy holatda 503 bilan javob beryapti)
# dagi qadimgi turkiy-qozoqcha lug'ati bilan tasdiqlandi/aniqlandi.
WORD_TR = {
    'qaγan': 'kağan (hükümdar)',
    'bilgä': 'bilge (akıllı, bilgili)',
    'üzä': 'üzerinde, üstünde',
    'kişi': 'kişi, insan',
    'täŋridä': "Tanrı'da, gökte",
    'bolmïş': 'olmuş',
    'namo': 'saygı, hürmet (Budist terim — Sanskritçe)',
    'türk': 'Türk',
    'täŋri': 'Tanrı, gök',
    'oγlï': 'oğlu',
    'olurtum': 'oturdum (tahta çıktım)',
    'etmiş': 'etmiş, yapmış',
    'men': 'ben',
    'män': 'ben',
    'maγan': 'Muğan (Muğan Kağan, kişi adı)',
    'i̇stämi': 'İstemi (İstemi Kağan, kişi adı)',
    'tegin': 'tigin (şehzade unvanı)',
    'otuz': 'otuz',
    'oγlan': 'oğlan, çocuk',
    'saγdïčlarï': 'sadık adamları, yakınları',
    'qunčuyïmqa': 'hatunuma, prensesime',
    'özdä': 'özünde, kendinde',
    'oγlïmqa': 'oğluma',
    'bökmädim': 'doymadım, kanmadım',
    'toñuquq': 'Tonyukuk (kişi adı)',
    'ben': 'ben',
    'özüm': 'kendim',
    'tabγač': 'Tabgaç (Çin, Çinliler)',
    'eliŋä': 'eline, ülkene',
    'qïlïntïm': 'hizmet ettim (bitig.kz: "qızmet ettim")',
    'bodun': 'budun, halk',
    'tabγačqa': "Çin'e, Tabgaç'a",
    'körür': 'görür',
    'erti': 'idi',
    'ečümiz': 'amcamız, atalarımız',
    'apamïz': 'atalarımız, dedelerimiz',
    'tört': 'dört',
    'buluŋuγ': 'yönü, bucağı (tört buluŋ — dört bucak/yön)',
    'qïsmïş': 'sıkıştırmış, baskı yapmış',
    'yïγmïş': 'toplamış',
    'yaymïş': 'yaymış',
    'basmïş': 'basmış, boyun eğdirmiş',
    'tarduš': 'Tarduş (boy/kabile adı)',
    'bodunïγ': 'budunu, halkı',
    'eti': 'etti, yaptı',
    'kül': 'Kül (kişi adının bir parçası — Kül Tigin, Kül Çor)',
    'čor': 'çor (askeri-idari unvan)',
    'kök': 'gök, mavi',
    'asra': 'altında, aşağıda',
    'yaγïz': 'yağız, kara, esmer',
    'yer': 'yer, toprak',
    'qïlïntuqda': 'yaratıldığında',
    'ekin': 'ikisi, her ikisi',
    'ara': 'ara, arası',
    'qïlïnmïş': 'yaratılmış',
    'oγlïnta': 'oğlunda, oğulları arasında',
    'ečüm': 'amcam, atam',
    'apam': 'atam, dedem',
    'bumïn': 'Bumın (Bumin Kağan, kişi adı)',
    'olurmïş': 'oturmuş (tahta çıkmış)',
    'täg': 'gibi, kadar',
    'ödkä': 'zamana, vakte',
    'sabïmïn': 'sözümü',
    'tükäti': 'tüketip, tamamlayıp',
    'eşidgil': 'işit!, dinle!',
    'bödkä': 'zamana, vakte',
    'yïlan': 'yılan',
    'yïl': 'yıl',
    'bešinč': 'beşinci',
    'bir': 'bir',
    'yaŋïqa': 'yeniye',
    'maŋa': 'bana',
    'böz': 'bez (kumaş)',
    'kärgäk': 'gerek, gerekli (kergek bol- — vefat etmek)',
    'bolup': 'olup',
    'täŋrim': 'Tanrım',
    'amtï': 'şimdi',
    'ökünürmen': 'pişman olurum',
    'yazuqda': 'günahta',
    'boşunu': 'kurtulup, bağışlanıp',
    'ötünürmen': 'rica ederim, yalvarırım',
    'manastar': 'Rabbim, Ulu Efendim (Maniheist dini hitap)',
    'hirza': 'affet, bağışla (Maniheist dua kalıbı: "Manastar hirza!")',
    'uyγur': 'Uygur',
    'yerintä': 'yerinde, topraklarında',
    'yaγlaqar': 'Yağlakar (Uygur hükümdar hanedanı)',
    'qan': 'han, kağan',
    'ata': 'ata, baba',
    'keltim': 'geldim',
    'qïrqïz': 'Kırgız',
    'boyla': 'boyla (idari-askeri unvan)',
    'qutluγ': 'kutlu (devlet kutuna sahip)',
    'yarγan': 'unvan/kişi adının parçası (bitig.kz: "Apa Yarğan Tarkan")',
    'tän': 'ten, vücut',
    'yarïn': 'yarın',
    'kečä': 'gece',
    'altun': 'altın',
    'örgin': 'taht',
    'olurupan': 'oturarak, oturup',
    'mäŋiläyür': 'sevinir',
    'anča': 'öyle, böyle',
    'biliŋlär': 'biliniz!',
    'ädgü': 'iyi',
    'but': 'Buda (Budist terim)',
    'darm': 'Darma/Dharma (Budist öğreti)',
    'saŋ': 'Sangha (Budist cemaat) — "but darm saŋ": Budizmin üç mücevheri',
    'bayat': 'Tanrı, Allah',
    'atï': 'adı',
    'birlä': 'ile, birlikte',
    'sözüg': 'sözü',
    'başladïm': 'başladım',
    'törütgän': 'yaratan',
    'egidgän': 'besleyen, büyüten',
    'kečürgän': 'yaşatan (törütgän egidgän kečürgän — Yaradan, Besleyen, Yaşatan)',
    'idim': 'efendim, Rabbim',
    'taγ': 'dağ',
    'taγqa': 'dağa',
    'qawuşmas': 'kavuşmaz',
    'kişigä': 'kişiye',
    'qawuşur': 'kavuşur',
}
