# Generated by Django 6.0.2 on 2026-03-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('title_original', models.CharField(blank=True, max_length=255, verbose_name='Asl nomi')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('year_end', models.IntegerField(blank=True, null=True, verbose_name='Tugash yili')),
                ('location', models.CharField(max_length=255, verbose_name='Joy')),
                ('script', models.CharField(choices=[('koktürk', "Ko'ktürk"), ('sogd', "So'g'd"), ("uyg'ur", "Uyg'ur"), ('arab', 'Arab'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Yozuv turi')),
                ('category', models.CharField(choices=[('bitiglar', 'Bitik toshlar'), ('qollanmalar', "Qo'llanmalar"), ('diniy', 'Diniy matnlar'), ('adabiy', 'Adabiy asarlar'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Kategoriya')),
                ('language', models.CharField(default="Ko'hna turkiy", max_length=100, verbose_name='Til')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('significance', models.TextField(blank=True, verbose_name='Ahamiyati')),
                ('full_text', models.TextField(blank=True, verbose_name="To'liq matn (asl yozuv)")),
                ('transliteration', models.TextField(blank=True, verbose_name='Transliteratsiya')),
                ('translation', models.TextField(blank=True, verbose_name='Tarjima')),
                ('image', models.URLField(blank=True, verbose_name='Rasm URL')),
                ('researchers', models.JSONField(default=list, verbose_name='Tadqiqotchilar')),
                ('bibliography', models.JSONField(default=list, verbose_name='Bibliografiya')),
                ('tags', models.JSONField(default=list, verbose_name='Teglar')),
                ('word_count', models.IntegerField(default=0, verbose_name="So'zlar soni")),
                ('line_count', models.IntegerField(default=0, verbose_name='Qatorlar soni')),
                ('status', models.CharField(default='Chop etilgan', max_length=100, verbose_name='Holat')),
                ('importance', models.IntegerField(default=3, verbose_name='Ahamiyat (1-5)')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('featured', models.BooleanField(default=False, verbose_name='Tanlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yodgorlik',
                'verbose_name_plural': 'Yodgorliklar',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Turkiy Yozma Yodgorliklar Korpusi', max_length=255)),
                ('site_subtitle', models.CharField(default="7-11 asrlardagi turkiy yozma merosning elektron to'plami", max_length=500)),
                ('about_text', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
