# Generated by Django 6.0.6 on 2026-06-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korpus', '0003_monument_author_email_monument_author_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monumentsubmission',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='submissions/docs/', verbose_name='Hujjat (PDF/Word/boshqa)'),
        ),
        migrations.AddField(
            model_name='monumentsubmission',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/images/', verbose_name='Rasm fayli (yuklash)'),
        ),
    ]
