# Generated by Django 4.2.30 on 2026-07-14 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('korpus', '0004_add_file_upload_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Kiritilgan login')),
                ('event', models.CharField(choices=[('login', 'Kirdi'), ('logout', 'Chiqdi'), ('failed', 'Muvaffaqiyatsiz urinish')], max_length=10, verbose_name='Hodisa')),
                ('via', models.CharField(choices=[('admin', 'Admin panel'), ('api', 'Sayt (API)')], default='admin', max_length=10, verbose_name='Qayerdan')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Qurilma (User-Agent)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_activities', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kirish tarixi',
                'verbose_name_plural': 'Kirish tarixi',
                'ordering': ['-timestamp'],
            },
        ),
    ]
