from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from korpus.models import Monument, SiteSettings

MONUMENTS = [
    {
        "title": "Tonyuquq bitigi",
        "titleOriginal": "𐱃𐰆𐰪𐰸𐰸",
        "year": 716,
        "yearEnd": 720,
        "location": "Mo'g'uliston, Nalayh tumani",
        "script": "koktürk",
        "category": "bitiglar",
        "language": "Ko'hna turkiy",
        "description": "Ikkinchi Ko'ktürk xoqonligining mashhur davlat arbobi va harbiy sarkardasi Tonyuquq sharafiga o'rnatilgan yodgorlik. Bu bitik Ko'ktürk yozuvida yozilgan eng qadimgi yodgorliklardan biri hisoblanadi.",
        "fullText": "𐱃𐰆𐰪𐰸𐰸 𐰉𐰃𐰠𐰏𐰀 𐱃𐰆𐰪𐰸𐰸 𐰉𐰃𐰠𐰏𐰀",
        "transliteration": "Tonyuquq biligä Tonyuquq biligä",
        "translation": "Dono Tonyuquq, aqlli Tonyuquq",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Tonyukuk_Inscription.jpg/640px-Tonyukuk_Inscription.jpg",
        "researchers": ["V.V. Radlov", "S.E. Malov", "H.N. Orkun"],
        "bibliography": ["Radlov V.V. (1895). Die alttürkischen Inschriften der Mongolei", "Malov S.E. (1951). Pamyatniki drevnetyurkskoy pismennosti"],
        "tags": ["Ko'ktürk", "harbiy", "siyosiy", "Mo'g'uliston"],
        "views": 245,
        "wordCount": 312,
        "lineCount": 62,
        "featured": True,
    },
    {
        "title": "Kültigin bitigi",
        "titleOriginal": "𐰚𐰇𐰠 𐱅𐰏𐰤",
        "year": 732,
        "yearEnd": None,
        "location": "Mo'g'uliston, Arxangay viloyati",
        "script": "koktürk",
        "category": "bitiglar",
        "language": "Ko'hna turkiy",
        "description": "Ikkinchi Ko'ktürk xoqonligining buyuk sarkardasi Kültigin sharafiga uning akasi Bilge Xoqon tomonidan o'rnatilgan ulkan yodgorlik. Turkiy xalqlar tarixi va madaniyatining eng muhim manbalaridan biri.",
        "fullText": "𐱅𐰤𐰼𐰃 𐰆𐰔𐰀 𐰸𐰆𐰞𐱃𐰀𐱃𐰢𐰽 𐱃𐰇𐰼𐰚 𐰉𐰃𐰠𐰏𐰀",
        "transliteration": "Tanri uza qultatmış Türk biligä",
        "translation": "Osmon tomonidan ulug'langan Türk donoligi",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Kul_Tigin_at_Khoshoo_Tsaidam.jpg/640px-Kul_Tigin_at_Khoshoo_Tsaidam.jpg",
        "researchers": ["V.V. Thomsen", "V.V. Radlov", "T. Tekin"],
        "bibliography": ["Thomsen V. (1896). Inscriptions de l'Orkhon déchiffrées", "Tekin T. (1968). A Grammar of Orkhon Turkic"],
        "tags": ["Ko'ktürk", "Orxun", "xoqonlik", "siyosiy"],
        "views": 389,
        "wordCount": 524,
        "lineCount": 94,
        "featured": True,
    },
    {
        "title": "Bilge Xoqon bitigi",
        "titleOriginal": "𐰉𐰃𐰠𐰏𐰀 𐰴𐰍𐰣",
        "year": 735,
        "yearEnd": None,
        "location": "Mo'g'uliston, Arxangay viloyati",
        "script": "koktürk",
        "category": "bitiglar",
        "language": "Ko'hna turkiy",
        "description": "Ikkinchi Ko'ktürk xoqonligining hukmdori Bilge Xoqon vafotidan keyin o'rnatilgan yodgorlik. Kültigin bitigiga o'xshash uslubda yozilgan bo'lib, xoqonlikning siyosiy va harbiy tarixi haqida ma'lumot beradi.",
        "fullText": "𐰉𐰃𐰠𐰏𐰀 𐰴𐰍𐰣 𐰉𐰃𐱅𐰃𐰏𐰃",
        "transliteration": "Biligä Qaγan bitigiˈ",
        "translation": "Bilge Xoqon bitigi",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Bilge_Kaghan_stele.jpg/640px-Bilge_Kaghan_stele.jpg",
        "researchers": ["V.V. Thomsen", "H.N. Orkun", "T. Tekin"],
        "bibliography": ["Orkun H.N. (1936-41). Eski Türk Yazıtları I-IV"],
        "tags": ["Ko'ktürk", "Orxun", "xoqon", "siyosiy"],
        "views": 312,
        "wordCount": 487,
        "lineCount": 88,
        "featured": True,
    },
    {
        "title": "Bugut bitigi",
        "titleOriginal": "Bugut",
        "year": 584,
        "yearEnd": None,
        "location": "Mo'g'uliston, Arxangay viloyati",
        "script": "sogd",
        "category": "bitiglar",
        "language": "So'g'd tili",
        "description": "Birinchi Ko'ktürk xoqonligi davrida so'g'd tilida yozilgan eng qadimgi tosh bitik. Bu yodgorlik o'sha davrda so'g'd tilining diplomatik munosabatlarda qo'llanilganligini ko'rsatadi.",
        "fullText": "",
        "transliteration": "",
        "translation": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Bugut_inscription.jpg/640px-Bugut_inscription.jpg",
        "researchers": ["V. A. Livshits", "L. Clark"],
        "bibliography": ["Livshits V.A. (1976). The Sogdian inscription of Bugut"],
        "tags": ["So'g'd", "birinchi xoqonlik", "Mo'g'uliston"],
        "views": 178,
        "wordCount": 148,
        "lineCount": 24,
        "featured": False,
    },
    {
        "title": "Shine-Usu bitigi",
        "titleOriginal": "Shine-Usu",
        "year": 759,
        "yearEnd": None,
        "location": "Mo'g'uliston, Zavxan viloyati",
        "script": "koktürk",
        "category": "bitiglar",
        "language": "Ko'hna turkiy",
        "description": "Uyg'ur xoqonligi hukmdori Mo'yinchur sharafiga o'rnatilgan yodgorlik. Uyg'ur xoqonligi tarixi haqidagi eng muhim manbalardan biri.",
        "fullText": "",
        "transliteration": "",
        "translation": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Orkhon_inscription_2.jpg/640px-Orkhon_inscription_2.jpg",
        "researchers": ["L. Bazin", "T. Moriyasu"],
        "bibliography": ["Bazin L. (1974). Les calendriers turcs anciens et médiévaux"],
        "tags": ["Uyg'ur", "xoqonlik", "Mo'g'uliston"],
        "views": 134,
        "wordCount": 396,
        "lineCount": 68,
        "featured": False,
    },
    {
        "title": "Yenisey bitiklari",
        "titleOriginal": "Yenisey",
        "year": 700,
        "yearEnd": 900,
        "location": "Sibir, Yenisey daryosi havzasi",
        "script": "koktürk",
        "category": "bitiglar",
        "language": "Ko'hna turkiy",
        "description": "Yenisey daryosi havzasida topilgan ko'plab tosh bitiklar to'plami. Bu bitiklar Ko'ktürk yozuvining Sibirdagi tarqalishini ko'rsatadi va qirg'iz qabilalari tarixi haqida ma'lumot beradi.",
        "fullText": "",
        "transliteration": "",
        "translation": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Yenisei_runic_inscription.jpg/640px-Yenisei_runic_inscription.jpg",
        "researchers": ["V.V. Radlov", "D.D. Vasiliev"],
        "bibliography": ["Vasiliev D.D. (1983). Graficheskiy fond pamyatnikov tyurkskoy runicheskoy pismennosti"],
        "tags": ["Ko'ktürk", "Sibir", "qirg'iz", "runa"],
        "views": 201,
        "wordCount": 230,
        "lineCount": 45,
        "featured": False,
    },
    {
        "title": "Talas bitiklari",
        "titleOriginal": "Talas",
        "year": 700,
        "yearEnd": 900,
        "location": "Qirg'iziston, Talas vodiysi",
        "script": "koktürk",
        "category": "bitiglar",
        "language": "Ko'hna turkiy",
        "description": "O'rta Osiyo, Talas vodiysida topilgan Ko'ktürk yozuvidagi bitiklar. Bu yodgorliklar Ko'ktürk yozuvining O'rta Osiyoda ham keng tarqalganligini isbotlaydi.",
        "fullText": "",
        "transliteration": "",
        "translation": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Old_Turkic_Talas_inscription.jpg/640px-Old_Turkic_Talas_inscription.jpg",
        "researchers": ["V.A. Kallaur", "S.E. Malov"],
        "bibliography": ["Malov S.E. (1959). Pamyatniki drevnetyurkskoy pismennosti Mongolii i Kirgizii"],
        "tags": ["Ko'ktürk", "O'rta Osiyo", "Talas", "runa"],
        "views": 167,
        "wordCount": 175,
        "lineCount": 38,
        "featured": False,
    },
    {
        "title": "Irq Bitig",
        "titleOriginal": "Irq Bitig",
        "year": 900,
        "yearEnd": None,
        "location": "Dunhuang, Xitoy (topilgan joy)",
        "script": "uyg'ur",
        "category": "qollanmalar",
        "language": "Ko'hna uyg'ur",
        "description": "Uyg'ur yozuvida yozilgan fol'binnoma — ko'hna turkiy qo'lyozma. Dunhuangdan topilgan bu asar falbin va bashorat san'atiga bag'ishlangan bo'lib, turkiy mifologiya va madaniyati haqida noyob ma'lumotlar beradi.",
        "fullText": "",
        "transliteration": "",
        "translation": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Irq_bitig.jpg/640px-Irq_bitig.jpg",
        "researchers": ["V.V. Radlov", "C.E. Bosworth"],
        "bibliography": ["Radlov V.V. (1891). Das Kudatku Bilik des Jusuf Chass-Hadschib aus Bäläsagun"],
        "tags": ["Uyg'ur", "Dunhuang", "fol'binnoma", "mifologiya"],
        "views": 223,
        "wordCount": 1650,
        "lineCount": 140,
        "featured": False,
    },
    {
        "title": "Xuastuanift",
        "titleOriginal": "Xuastuanift",
        "year": 800,
        "yearEnd": 900,
        "location": "Turfon, Xitoy (topilgan joy)",
        "script": "uyg'ur",
        "category": "diniy",
        "language": "Ko'hna uyg'ur",
        "description": "Moniy dini e'tiqodchilari uchun yozilgan tavba duosi matni. Bu qo'lyozma ko'hna turkiy tildagi dini adabiyotning nodir namunasidir va Turfon topilmalarining muhim qismi hisoblanadi.",
        "fullText": "",
        "transliteration": "",
        "translation": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Manichaean_manuscript_Turfan.jpg/640px-Manichaean_manuscript_Turfan.jpg",
        "researchers": ["A. von Le Coq", "W. Bang", "A. Gabain"],
        "bibliography": ["Le Coq A. von (1911-12). Chuastuanift, ein Sündenbekenntnis der manichäischen Auditores"],
        "tags": ["Uyg'ur", "Moniylik", "din", "Turfon"],
        "views": 156,
        "wordCount": 2840,
        "lineCount": 220,
        "featured": False,
    },
    {
        "title": "Altun Yoruq",
        "titleOriginal": "Altun Yaruk Sudur",
        "year": 930,
        "yearEnd": 960,
        "location": "Turfon, Xitoy (topilgan joy)",
        "script": "uyg'ur",
        "category": "diniy",
        "language": "Ko'hna uyg'ur",
        "description": "Buddaviy dinining Oltin yorug' sutrasini uyg'ur tiliga tarjima qilgan keng hajmli asar. Bu qo'lyozma ko'hna uyg'ur yozuvidagi buddaviy adabiyotning eng muhim yodgorliklaridan biri.",
        "fullText": "",
        "transliteration": "",
        "translation": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Uyghur_Buddhist_manuscript.jpg/640px-Uyghur_Buddhist_manuscript.jpg",
        "researchers": ["A. von Le Coq", "W. Radloff", "K. Röhrborn"],
        "bibliography": ["Röhrborn K. (1977-). Uigurisches Wörterbuch"],
        "tags": ["Uyg'ur", "Buddizm", "din", "Turfon", "sutra"],
        "views": 189,
        "wordCount": 18500,
        "lineCount": 1240,
        "featured": False,
    },
    {
        "title": "Mo'yinchur bitigi",
        "titleOriginal": "Mo'yinchur",
        "year": 759,
        "yearEnd": None,
        "location": "Mo'g'uliston",
        "script": "koktürk",
        "category": "bitiglar",
        "language": "Ko'hna turkiy",
        "description": "Uyg'ur xoqoni Mo'yinchur (Bayancho'r) o'zining harbiy yurishlari va siyosiy faoliyati haqida yozdirgan bitik. Uyg'ur xoqonligi tarixi uchun birlamchi manba.",
        "fullText": "",
        "transliteration": "",
        "translation": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Orkhon_inscription_3.jpg/640px-Orkhon_inscription_3.jpg",
        "researchers": ["H.N. Orkun", "T. Tekin"],
        "bibliography": ["Tekin T. (1968). A Grammar of Orkhon Turkic"],
        "tags": ["Ko'ktürk", "Uyg'ur", "xoqon", "Mo'g'uliston"],
        "views": 145,
        "wordCount": 418,
        "lineCount": 72,
        "featured": False,
    },
    {
        "title": "Turfon qo'lyozmalari",
        "titleOriginal": "Turfan Handschriften",
        "year": 800,
        "yearEnd": 1000,
        "location": "Turfon, Xitoy",
        "script": "uyg'ur",
        "category": "qollanmalar",
        "language": "Ko'hna uyg'ur",
        "description": "Turfon shahrida topilgan yuzlab ko'hna uyg'ur qo'lyozmalari to'plami. Bu qo'lyozmalar buddaviy, moniy va nasroniy dinlariga oid matnlarni, shuningdek dunyoviy asarlarni o'z ichiga oladi.",
        "fullText": "",
        "transliteration": "",
        "translation": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Uighur_Turfan_manuscript.jpg/640px-Uighur_Turfan_manuscript.jpg",
        "researchers": ["A. Grünwedel", "A. von Le Coq", "A. Gabain"],
        "bibliography": ["Gabain A. von (1941). Alttürkische Grammatik"],
        "tags": ["Uyg'ur", "Turfon", "qo'lyozma", "ko'p din"],
        "views": 198,
        "wordCount": 8600,
        "lineCount": 620,
        "featured": False,
    },
    {
        "title": "Suji bitigi",
        "titleOriginal": "Suji",
        "year": 940,
        "yearEnd": None,
        "location": "Mo'g'uliston",
        "script": "uyg'ur",
        "category": "bitiglar",
        "language": "Ko'hna uyg'ur",
        "description": "Uyg'ur yozuvida bitilgan tosh yodgorlik. Ko'ktürk yozuvidan uyg'ur yozuviga o'tish davrini aks ettiruvchi muhim manba.",
        "fullText": "",
        "transliteration": "",
        "translation": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Orkhon_valley_stele.jpg/640px-Orkhon_valley_stele.jpg",
        "researchers": ["T. Moriyasu", "A. Ochir"],
        "bibliography": ["Moriyasu T. (2004). Die Geschichte des uigurischen Manichäismus an der Seidenstrasse"],
        "tags": ["Uyg'ur", "Mo'g'uliston", "tosh bitik"],
        "views": 112,
        "wordCount": 260,
        "lineCount": 46,
        "featured": False,
    },
    {
        "title": "Qutadg'u Bilig",
        "titleOriginal": "قوتادغو بیلیگ",
        "year": 1069,
        "yearEnd": None,
        "location": "Koshg'ar (Xitoy)",
        "script": "arab",
        "category": "adabiy",
        "language": "Qoraxoniy turkiy",
        "description": "Yusuf Xos Hojib tomonidan Koshg'arda yozilgan ulkan siyosiy-ta'limiy doston. 'Baxtli bo'lish bilimi' ma'nosini anglatuvchi bu asar O'rta Osiyo va turkiy adabiyotning nodir durdonalaridan biri.",
        "fullText": "قوتادغو بیلیگ یوسف خاص حاجب تارافیندان یازیلغان",
        "transliteration": "Qutadg'u Bilig Yusuf Xos Hojib tarafından yazılg'an",
        "translation": "Yusuf Xos Hojib tomonidan yozilgan Baxtli bo'lish bilimi",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Qutadghu_bilig_Herat_manuscript.jpg/640px-Qutadghu_bilig_Herat_manuscript.jpg",
        "researchers": ["V.V. Radlov", "R.R. Arat", "A.K. Borovkov"],
        "bibliography": ["Arat R.R. (1947). Kutadgu Bilig I: Metin", "Borovkov A.K. (1963). Leksika sredneaziatskogo tefsira XII-XIII vv."],
        "tags": ["Qoraxoniy", "adabiyot", "siyosat", "ta'lim", "doston"],
        "views": 467,
        "wordCount": 67000,
        "lineCount": 4800,
        "featured": True,
    },
    {
        "title": "Devonu Lug'atit Turk",
        "titleOriginal": "دیوان لغات الترک",
        "year": 1072,
        "yearEnd": 1074,
        "location": "Bog'dod (Iroq)",
        "script": "arab",
        "category": "qollanmalar",
        "language": "Ko'hna turkiy (lug'at)",
        "description": "Mahmud Koshg'ariy tomonidan arab tilidagi qomusiy lug'at. Turkiy tillar va urf-odatlar haqidagi eng qadimiy va to'liq ilmiy asar. Ko'hna turkiy tilning grammatikasi, leksikasi va folklori haqida bebaho ma'lumotlar beradi.",
        "fullText": "دیوان لغات الترک محمود الکاشغری",
        "transliteration": "Devonu Lug'atit Turk - Mahmud Koshg'ariy",
        "translation": "Turk tillari devoni - Mahmud Koshg'ariy tomonidan",
        "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Mahmud_al-Kashgari_world_map.jpg",
        "researchers": ["C. Brockelmann", "B. Atalay", "R. Dankoff"],
        "bibliography": ["Atalay B. (1939-41). Divanü Lûgat-it-Türk Tercümesi I-III", "Dankoff R. (1982). Mahmud al-Kashgari: Compendium of the Turkic Dialects"],
        "tags": ["Qoraxoniy", "lug'at", "tilshunoslik", "folklor", "qomus"],
        "views": 534,
        "wordCount": 9000,
        "lineCount": 680,
        "featured": True,
    },
]


class Command(BaseCommand):
    help = "Ma'lumotlar bazasini boshlang'ich ma'lumotlar bilan to'ldiradi"

    def add_arguments(self, parser):
        parser.add_argument(
            '--reset',
            action='store_true',
            help='Mavjud yodgorliklarni o\'chirib, qayta yaratadi',
        )

    def handle(self, *args, **options):
        if options['reset']:
            Monument.objects.all().delete()
            self.stdout.write(self.style.WARNING('Barcha yodgorliklar o\'chirildi.'))

        # Create superuser if not exists
        if not User.objects.filter(username='admin').exists():
            User.objects.create_superuser('admin', 'admin@korpus.uz', 'admin123')
            self.stdout.write(self.style.SUCCESS('Superuser yaratildi: admin / admin123'))

        if not User.objects.filter(username='editor').exists():
            editor = User.objects.create_user('editor', 'editor@korpus.uz', 'editor123')
            editor.is_staff = True
            editor.save()
            self.stdout.write(self.style.SUCCESS('Muharrir yaratildi: editor / editor123'))

        # Seed site settings
        SiteSettings.objects.get_or_create(
            pk=1,
            defaults={
                'site_title': 'Turkiy Yozma Yodgorliklar Korpusi',
                'site_subtitle': "VII–XI asrlardagi turkiy yozma merosning elektron to'plami",
                'about_text': (
                    "Bu korpus VII–XI asrlarda yaratilgan turkiy yozma yodgorliklarni o'rganish va "
                    "targ'ib qilish maqsadida yaratilgan. Ko'ktürk, So'g'd, Uyg'ur va Arab "
                    "yozuvlarida bitilgan yodgorliklar haqida batafsil ma'lumot olishingiz mumkin."
                ),
            }
        )

        # Seed monuments — convert camelCase to snake_case for model fields
        key_map = {
            'titleOriginal': 'title_original',
            'yearEnd': 'year_end',
            'fullText': 'full_text',
            'wordCount': 'word_count',
            'lineCount': 'line_count',
        }
        created = 0
        for raw in MONUMENTS:
            data = {key_map.get(k, k): v for k, v in raw.items()}
            if not Monument.objects.filter(title=data['title']).exists():
                Monument.objects.create(**data)
                created += 1

        self.stdout.write(self.style.SUCCESS(
            f'{created} ta yangi yodgorlik qo\'shildi. '
            f'Jami: {Monument.objects.count()} ta yodgorlik.'
        ))
